name: bower_semver
version: 1.0.0
author: Dart Team <misc@dartlang.org>, Chrome Dev Editor Team
description: >
 Versions and version constraints implementing Bower versioning policy.
 Based on https://github.com/dart-lang/pub_semver.
homepage: http://github.com/ussuri/bower_semver
dependencies:
  collection: ">=0.9.0 <2.0.0"
dev_dependencies:
  unittest: ">=0.9.0 <0.12.0"
environment:
  sdk: ">=1.0.0 <2.0.0"
